### ISSUE TITLE
Request for contribution

### ISSUE THREAD

**Issue by kfragkedaki** [prabhakar267/aware#17]
I found interesting your app and I'd like to contribute to this. Is there anything that needs improvement?

**Comment by prabhakar267** [comment]
@kfragkedaki Thank you for showing interest in the project.
You can either work on the existing [open issue(s)](https://github.com/prabhakar267/aware/issues) or can suggest any new feature you would like to work on.

Maybe @mbad0la or @Swati4star could chip in some new ideas for the project.

**Comment by mbad0la** [comment]
Push notification on whenever the Air crosses a certain "quality" threshold?

**Comment by kfragkedaki** [comment]
Ok, I will contribute to that. Thank you for your response.
