### ISSUE TITLE
Integrate top priority messages in admin panel

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/aware#4]
Use the route ```get-top-priorities``` to get the top K messages (messages with the highest score) in the admin panel instead of static messages

**Comment by AmoliShah** [comment]
I want to work on this issue. @prabhakar267 Can you please help me out?

**Comment by prabhakar267** [comment]
@AmoliShah you need to start with completing the setup of the server of the project. Follow the instructions given here (https://github.com/prabhakar267/aware/tree/master/server#setup)

After you have completed the setup, check this route ```/dashboard```, you need to make the changes in the code for this route.

**Comment by AmoliShah** [comment]
ok thanks. @prabhakar267

**Comment by abhanshgiri21** [comment]
hi,
i would like to work on this issue , how can i do this? @prabhakar267

**Comment by prabhakar267** [comment]
@AmoliShah  was supposed to work on this but since I don't see any progress in his fork or in terms of communication for 10 days.

@abhanshgiri21 you can start working on this. As i mentioned above, follow those steps and let me know if you face any problem in the same.

**Comment by johnhorsema** [comment]
@prabhakar267 I just got started on this issue and your project.
I believe you should add a 'Troubleshoot' section in your README here (https://github.com/prabhakar267/aware/tree/master/server#setup)
with http://stackoverflow.com/questions/22252397/importerror-no-module-named-mysqldb

**Comment by prabhakar267** [comment]
@johnhorsema I think you didn't follow the instructions properly. Since I can see MySQL dependency in requirements.txt (https://github.com/prabhakar267/aware/blob/master/server/requirements.txt#L8)

Still if you faced some error let me know I will add a troubleshoot section for other people

**Comment by ollyjohn** [comment]
Is this still up for grabs?  Not seeing any comments saying it's been completed..

**Comment by prabhakar267** [comment]
@ollyjohn Yes you can work on it

**Comment by shreab373** [comment]
is anyone working on this still? if not can i take it?

**Comment by prabhakar267** [comment]
@shreab373 you can work on it
Let me know if you have any queries or want any help

**Comment by kjng** [comment]
Doesn't the admin page already make the ajax request to the /get-top-priorities endpoint?

**Comment by prabhakar267** [comment]
@mbad0la

**Comment by mbad0la** [comment]
@kjng it does, but we need a function that gets the top K messages rather than the [top three](https://github.com/prabhakar267/aware/blob/4d3b674013c0acb969e0cf0104b0695e9535fbca/server/templates/admin.html#L86)

**Comment by infinityl00p** [comment]
might be the 5th person to ask, but is this issue still open? this would be my second contribution so i'm still a beginner but more than happy to help! @prabhakar267

**Comment by prabhakar267** [comment]
@infinityl00p yes you can work on this issue :laughing: 
Feel free to ping me if you have any queries

**Comment by kjng** [comment]
For @infinityl00p to work on this, can you clarify if/how you want a user to interact with this K message function? @prabhakar267

**Comment by prabhakar267** [comment]
@infinityl00p @kjng 
You would need to edit the ```/dashboard``` route and the ```admin``` template for resolving the issue

**Comment by anusha94** [comment]
is there any way I can help with this issue?

**Comment by kjng** [comment]
Probably you could work on it, although it's unclear if there needs to be ui elements added so one could use the function.

**Comment by SteveAndrewArcher** [comment]
instead of being the 100th person to ask, I just went ahead and did it :)

**Comment by prabhakar267** [comment]
Finally this issue has been fixed :laughing:
@SteveAndrewArcher :+1:
